### ISSUE TITLE
Get error after changing system locale in livehelperchat

### ISSUE THREAD

**Issue by Samurais** [LiveHelperChat/livehelperchat#1204]
# Description

I would like to set the locale to "zh_ZH" for Chinese, so, after saving it with the "configuration"

![image](https://user-images.githubusercontent.com/3538629/38022968-9df5a452-32b3-11e8-8f27-87f19a1b8361.png)

Then, logout and login again, the home page is lost, what I see is a blank screen.

And in the background, the trace is like this. 
```
livehelperchat_1      | 45.76.53.37 - - [10/Mar/2018:03:22:57 +0000] "GET /design/defaulttheme/images/general/logo.png HTTP/1.1" 200 3767
livehelperchat_1      | 45.76.53.37 - - [10/Mar/2018:03:22:59 +0000] "POST /index.php/site_admin/user/login HTTP/1.1" 302 0
livehelperchat_1      | 10/Mar/2018:03:23:00 +0000 [ERROR 0 /index.php/site_admin/] PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function simplexml_load_string() in /srv/ezcomponents/Translation/src/backends/ts_backend.php:233
livehelperchat_1      | Stack trace:
livehelperchat_1      | #0 /srv/ezcomponents/Translation/src/backends/ts_backend.php(395): ezcTranslationTsBackend->openTranslationFile('zh_ZH', 'SimpleXMLIterat...')
livehelperchat_1      | #1 /srv/lib/core/lhcore/lhtranslation.php(125): ezcTranslationTsBackend->initReader('zh_ZH')
livehelperchat_1      | #2 /srv/lib/core/lhcore/lhtranslation.php(28): erTranslationClassLhTranslation->updateCache()
livehelperchat_1      | #3 /srv/lib/core/lhcore/lhtranslation.php(193): erTranslationClassLhTranslation->__construct()
livehelperchat_1      | #4 /srv/design/defaulttheme/tpl/lhchat/lists/open_active_chat_tab.tpl.php(6): erTranslationClassLhTranslation::getInstance()
livehelperchat_1      | #5 /srv/design/defaulttheme/tpl/lhfront/default.tpl.php(31): include('/srv/design/def...')
livehelperchat_1      | #6 /srv/lib/core/lhtpl/tpl.php(535): include('/srv/design/def...')
livehelperchat_1      | #7 /srv/lib/core/lhtpl/tpl.php(510): erLhcoreClassTemplate->fetchExecute('/srv/design/def...')
livehelperchat_1      | #8 /srv/modules/lhfront/default.php(22): ...
```

So, how to fix this problem? do I miss some configurations?

**Comment by remdex** [comment]
PHP extension to work with xml is missing.
