### ISSUE TITLE
Database passwords are being escaped

### ISSUE THREAD

**Issue by tmbenhura** [LiveHelperChat/livehelperchat#1342]
When connecting using passwords with a percentage sign e.g, PASS%WORD the password is escaped when it is fetched from the config and becomes PASS\xWORD .

This will result in a "Cannot connect to database. If you are installing application please use /index.php/install/install url. If you keep getting this error please check that application can write to cache folder and cgi.fix_pathinfo = 1" error.

```
[REMOVED] PDOException: SQLSTATE[HY000] [1045] Access denied for user 'username'@'localhost' (using password: YES) in /path-to-livehelp/ezcomponents/Database/src/handler.php:88
Stack trace:
#0 /path-to-livehelp/ezcomponents/Database/src/handler.php(88): PDO->__construct('mysql:dbname=...', 'username', 'PASS\xWORD', NULL)
#1 /path-to-livehelp/ezcomponents/Database/src/handlers/mysql.php(114): ezcDbHandler->__construct(Array, 'mysql:dbname=ba...')
#2 /path-to-livehelp/ezcomponents/Database/src/factory.php(162): ezcDbHandlerMysql->__construct(Array)
#3 /path-to-livehelp/lib/core/lhcore/lhdb.php(54): ezcDbFactory::create(Array)
#4 /path-to-livehelp/ezcomponents/Base/src/init.php(120): erLhcoreClassLazyDatabaseConfiguration::configureObject(false)
#5 /path-to-livehelp/ezcomponents/Database/src/instance.php(96): ezcBaseInit::fetchConfig('ezcInitDatabase...', false)
#6 /path-to-livehelp/lib/core/lhchat/lhchat.php(1185): ezcDbInstance::get()
#7 /path-to-livehelp/lib/models/lhchat/erlhcoreclassmodelchatconfig.php(25): erLhcoreClassChat::getSession()
#8 /path-to-livehelp/modules/lhchat/getstatus.php(11): erLhcoreClassModelChatConfig::fetch('hide_disabled_d...')
#9 /path-to-livehelp/lib/core/lhcore/lhmodule.php(97): include('/REMOVED...')
#10 /path-to-livehelp/lib/core/lhcore/lhmodule.php(485): erLhcoreClassModule::runModule()
#11 /path-to-livehelp/index.php(39): erLhcoreClassModule::moduleInit()
#12 {main}
```

**Comment by remdex** [comment]
We tried locally and could not reproduce...
