### ISSUE TITLE
npm install && npm run build && npm run build-ie fails

### ISSUE THREAD

**Issue by fatrolls** [LiveHelperChat/livehelperchat#1492]
Something to do with the spread operators missing on 
Node v6.17.1 (latest on CentOS).
npm v3.10.10 (latest on CentOS).

Here is a stackoverflow Q&A how to fix it.. need to modify the `.babelrc` file.

https://stackoverflow.com/questions/56003497/nodejs-problem-with-spread-operators-unexprected-token

here is the fix

` "plugins": [["transform-object-rest-spread", { "useBuiltIns": true }]]`

you also need to install `npm install --save-dev babel-plugin-transform-object-rest-spread`

```
[root@chatsite livechat]# cd design/defaulttheme/widget/react-app && npm install && npm run build && npm run build-ie
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/watchpack-chokidar2/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/webpack-dev-server/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN empty-project@1.0.0 No repository field.

> empty-project@1.0.0 build /var/www/chatsite.com/public_html/livechat/design/defaulttheme/widget/react-app
> webpack -p --mode production && cp -v dist/*.js ../../js/widgetv2/

Hash: 1ced34ec5e972fba05d9
Version: webpack 4.43.0
Time: 572ms
Built at: 06/24/2020 12:26:19 AM
 1 asset
Entrypoint main = react.app.js
[0] ./src/react.app.js 3.51 KiB {0} [not cacheable] [built] [failed] [1 error]

ERROR in ./src/react.app.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
/var/www/chatsite.com/public_html/livechat/design/defaulttheme/widget/react-app/node_modules/schema-utils/dist/util/hints.js:16
  const currentSchema = { ...schema };
                          ^^^

SyntaxError: Unexpected token ...
    at NativeCompileCache._moduleCompile (/var/www/chatsite.com/public_html/livechat/design/defaulttheme/widget/react-app/node_modules/v8-compile-cache/v8-compile-cache.js:242:18)
    at Module._compile (/var/www/chatsite.com/public_html/livechat/design/defaulttheme/widget/react-app/node_modules/v8-compile-cache/v8-compile-cache.js:186:36)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (/var/www/chatsite.com/public_html/livechat/design/defaulttheme/widget/react-app/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/var/www/chatsite.com/public_html/livechat/design/defaulttheme/widget/react-app/node_modules/schema-utils/dist/ValidationError.js:11:5)
    at Module._compile (/var/www/chatsite.com/public_html/livechat/design/defaulttheme/widget/react-app/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (/var/www/chatsite.com/public_html/livechat/design/defaulttheme/widget/react-app/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/var/www/chatsite.com/public_html/livechat/design/defaulttheme/widget/react-app/node_modules/schema-utils/dist/validate.js:14:47)
    at Module._compile (/var/www/chatsite.com/public_html/livechat/design/defaulttheme/widget/react-app/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (/var/www/chatsite.com/public_html/livechat/design/defaulttheme/widget/react-app/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/var/www/chatsite.com/public_html/livechat/design/defaulttheme/widget/react-app/node_modules/schema-utils/dist/index.js:3:18)
    at Module._compile (/var/www/chatsite.com/public_html/livechat/design/defaulttheme/widget/react-app/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (/var/www/chatsite.com/public_html/livechat/design/defaulttheme/widget/react-app/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/var/www/chatsite.com/public_html/livechat/design/defaulttheme/widget/react-app/node_modules/babel-loader/lib/index.js:43:25)
    at Module._compile (/var/www/chatsite.com/public_html/livechat/design/defaulttheme/widget/react-app/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)

npm ERR! Linux 3.10.0-1062.4.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! empty-project@1.0.0 build: `webpack -p --mode production && cp -v dist/*.js ../../js/widgetv2/`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the empty-project@1.0.0 build script 'webpack -p --mode production && cp -v dist/*.js ../../js/widgetv2/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the empty-project package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack -p --mode production && cp -v dist/*.js ../../js/widgetv2/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs empty-project
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls empty-project
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/chatsite.com/public_html/livechat/design/defaulttheme/widget/react-app/npm-debug.log
```

**Comment by remdex** [comment]
Just use newer node version. On my env I have 10.21.0 and it works just fine...

**Comment by fatrolls** [comment]
Confirmed works now after I ran these commands

```
yum install -y gcc-c++ make
curl -sL https://rpm.nodesource.com/setup_12.x | sudo -E bash -
```


```
[root@chatsite livechat]# cd design/defaulttheme/widget/react-app && npm install && npm run build && npm run build-ie
npm WARN empty-project@1.0.0 No repository field.
npm WARN The package html-webpack-template is included as both a dev and production dependency.
npm WARN The package xwiper is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 902 packages in 14.39s

26 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


> empty-project@1.0.0 build /var/www/chatsite.com/public_html/livechat/design/defaulttheme/widget/react-app
> webpack -p --mode production && cp -v dist/*.js ../../js/widgetv2/

Building unminified package for Native JavaScript for Bootstrap 4 v2.0.27 ..
Included modules: Modal, Dropdown, Tab
Build complete!

Hash: 09b10cb794be6da8442b
Version: webpack 4.43.0
Time: 34853ms
Built at: 06/24/2020 1:04:06 AM
                    Asset      Size  Chunks                                Chunk Names
1.16b5060d8afe91d2a268.js  63.6 KiB       1  [emitted] [immutable]
2.c8d9f7e64d17b337e542.js  6.48 KiB       2  [emitted] [immutable]
3.1754658a8bc73c4e1efc.js  2.76 KiB       3  [emitted] [immutable]
4.b465e388dba89bf57b99.js  12.6 KiB       4  [emitted] [immutable]
5.eaf0d40adb242eb8b650.js  2.27 KiB       5  [emitted] [immutable]
             react.app.js   466 KiB       0  [emitted]              [big]  main
Entrypoint main [big] = react.app.js
  [2] ./src/lib/helperFunctions.js 4.24 KiB {0} [built]
  [8] ./src/constants/chat-status.js 655 bytes {0} [built]
  [9] ./src/actions/chatActions.js 16.8 KiB {0} [built]
 [12] ./node_modules/react-redux/es/index.js + 24 modules 50.3 KiB {0} [built]
      |    25 modules
 [24] (webpack)/buildin/global.js 472 bytes {0} [built]
 [30] ./node_modules/react-i18next/dist/es/withTranslation.js + 2 modules 8.9 KiB {0} [built]
      |    3 modules
 [45] ./src/components/StartChat.js + 3 modules 34 KiB {0} [built]
      |    4 modules
 [63] (webpack)/buildin/harmony-module.js 573 bytes {0} [built]
 [99] ./src/react.app.js + 30 modules 343 KiB {0} [built]
      | ./src/react.app.js 345 bytes [built]
      | ./src/App.js 1.82 KiB [built]
      | ./src/store/index.js 513 bytes [built]
      | ./src/reducers/index.js 162 bytes [built]
      | ./src/store/chatWidgetListener.js 7.69 KiB [built]
      | ./src/reducers/chatWidgetReducer.js 13.5 KiB [built]
      | ./src/i18n.js 182 bytes [built]
      | ./src/constants/action-types.js 369 bytes [built]
      |     + 23 hidden modules
[100] ./src/extensions/nodejs/nodeJSChat.js 5.32 KiB {5} [built]
[130] ./src/components/VoiceMessage.js + 1 modules 33.6 KiB {4} [built]
      |    2 modules
    + 130 hidden modules

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  react.app.js (466 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (466 KiB)
      react.app.js

'dist/1.16b5060d8afe91d2a268.js' -> '../../js/widgetv2/1.16b5060d8afe91d2a268.js'
'dist/2.c8d9f7e64d17b337e542.js' -> '../../js/widgetv2/2.c8d9f7e64d17b337e542.js'
'dist/3.1754658a8bc73c4e1efc.js' -> '../../js/widgetv2/3.1754658a8bc73c4e1efc.js'
'dist/4.b465e388dba89bf57b99.js' -> '../../js/widgetv2/4.b465e388dba89bf57b99.js'
'dist/5.eaf0d40adb242eb8b650.js' -> '../../js/widgetv2/5.eaf0d40adb242eb8b650.js'
'dist/react.app.js' -> '../../js/widgetv2/react.app.js'

> empty-project@1.0.0 build-ie /var/www/chatsite.com/public_html/livechat/design/defaulttheme/widget/react-app
> webpack -p --mode production --config webpack.config.ie.js && cp -v dist/*.js ../../js/widgetv2/

Building unminified package for Native JavaScript for Bootstrap 4 v2.0.27 ..
Included modules: Modal, Dropdown, Tab
Build complete!

Hash: 62c8e6bc7771cb02e0eb
Version: webpack 4.43.0
Time: 19636ms
Built at: 06/24/2020 1:06:17 AM
                       Asset      Size  Chunks                                Chunk Names
1.a2a8e0d794e2c779ca08.ie.js  63.6 KiB       1  [emitted] [immutable]
2.ca8ee57b2db57f3710f1.ie.js  6.49 KiB       2  [emitted] [immutable]
3.eebc212782763a6ee009.ie.js  2.76 KiB       3  [emitted] [immutable]
4.7e87b62cd1906363c474.ie.js  12.6 KiB       4  [emitted] [immutable]
5.f0d32c31257fb82cd905.ie.js  2.27 KiB       5  [emitted] [immutable]
             react.app.ie.js   584 KiB       0  [emitted]              [big]  main
Entrypoint main [big] = react.app.ie.js
  [3] ./src/lib/helperFunctions.js 4.24 KiB {0} [built]
 [11] ./src/constants/chat-status.js 655 bytes {0} [built]
 [12] ./src/actions/chatActions.js 16.8 KiB {0} [built]
 [24] ./node_modules/react-redux/es/index.js + 24 modules 50.3 KiB {0} [built]
      |    25 modules
 [84] (webpack)/buildin/global.js 472 bytes {0} [built]
[139] ./node_modules/react-i18next/dist/es/withTranslation.js + 2 modules 8.9 KiB {0} [built]
      |    3 modules
[195] ./src/components/StartChat.js + 3 modules 34 KiB {0} [built]
      |    4 modules
[438] (webpack)/buildin/harmony-module.js 573 bytes {0} [built]
[474] ./src/react.app.ie.js + 30 modules 343 KiB {0} [built]
      | ./src/react.app.ie.js 402 bytes [built]
      | ./src/App.js 1.82 KiB [built]
      | ./src/store/index.js 513 bytes [built]
      | ./src/reducers/index.js 162 bytes [built]
      | ./src/store/chatWidgetListener.js 7.69 KiB [built]
      | ./src/reducers/chatWidgetReducer.js 13.5 KiB [built]
      | ./src/i18n.js 182 bytes [built]
      | ./src/constants/action-types.js 369 bytes [built]
      |     + 23 hidden modules
[475] ./src/extensions/nodejs/nodeJSChat.js 5.32 KiB {5} [built]
[505] ./src/components/VoiceMessage.js + 1 modules 33.6 KiB {4} [built]
      |    2 modules
    + 505 hidden modules

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  react.app.ie.js (584 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (584 KiB)
      react.app.ie.js

'dist/1.16b5060d8afe91d2a268.js' -> '../../js/widgetv2/1.16b5060d8afe91d2a268.js'
'dist/1.a2a8e0d794e2c779ca08.ie.js' -> '../../js/widgetv2/1.a2a8e0d794e2c779ca08.ie.js'
'dist/2.c8d9f7e64d17b337e542.js' -> '../../js/widgetv2/2.c8d9f7e64d17b337e542.js'
'dist/2.ca8ee57b2db57f3710f1.ie.js' -> '../../js/widgetv2/2.ca8ee57b2db57f3710f1.ie.js'
'dist/3.1754658a8bc73c4e1efc.js' -> '../../js/widgetv2/3.1754658a8bc73c4e1efc.js'
'dist/3.eebc212782763a6ee009.ie.js' -> '../../js/widgetv2/3.eebc212782763a6ee009.ie.js'
'dist/4.7e87b62cd1906363c474.ie.js' -> '../../js/widgetv2/4.7e87b62cd1906363c474.ie.js'
'dist/4.b465e388dba89bf57b99.js' -> '../../js/widgetv2/4.b465e388dba89bf57b99.js'
'dist/5.eaf0d40adb242eb8b650.js' -> '../../js/widgetv2/5.eaf0d40adb242eb8b650.js'
'dist/5.f0d32c31257fb82cd905.ie.js' -> '../../js/widgetv2/5.f0d32c31257fb82cd905.ie.js'
'dist/react.app.ie.js' -> '../../js/widgetv2/react.app.ie.js'
'dist/react.app.js' -> '../../js/widgetv2/react.app.js'
[root@chatsite react-app]#
```
