### ISSUE TITLE
get "emergency or scheduled maintenance window" message

### ISSUE THREAD

**Issue by comsyspro** [LiveHelperChat/livehelperchat#2060]
since today i can't login to lhc and get this message. what could be the issue?

```
We’ll be back soon!
This service is currently unavailable due to an emergency or scheduled maintenance window. The service will be back online within the next two hours. Sorry for the inconvenience.

— Online Service Support Team
```

in the background we are running a weekly crontab which updates lhc. in the last year this has worked without issues. could there be the problem?

here is default.log

```
Mar 01 09:52:02 [Warning] [default] [default] {
    "message": "A query failed internally in Persistent Object: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'livehelperchat.lhc_mailconv_conversation' doesn't exist Query: 'SELECT `lhc_mailconv_conversation`.`id`, `lhc_mailconv_conversation`.`remarks`, `lhc_mailconv_conversation`.`date`, `lhc_mailconv_conversation`.`from_address`, `lhc_mailconv_conversation`.`from_name`, `lhc_mailconv_conversation`.`body`, `lhc_mailconv_conversation`.`subject`, `lhc_mailconv_conversation`.`mail_variables`, `lhc_mailconv_conversation`.`lang`, `lhc_mailconv_conversation`.`phone`, `lhc_mailconv_conversation`.`transfer_uid`, `lhc_mailconv_conversation`.`start_type`, `lhc_mailconv_conversation`.`lr_time`, `lhc_mailconv_conversation`.`dep_id`, `lhc_mailconv_conversation`.`ctime`, `lhc_mailconv_conversation`.`user_id`, `lhc_mailconv_conversation`.`status`, `lhc_mailconv_conversation`.`last_message_id`, `lhc_mailconv_conversation`.`mailbox_id`, `lhc_mailconv_conversation`.`message_id`, `lhc_mailconv_conversation`.`priority`, `lhc_mailconv_conversation`.`priority_asc`, `lhc_mailconv_conversation`.`udate`, `lhc_mailconv_conversation`.`total_messages`, `lhc_mailconv_conversation`.`match_rule_id`, `lhc_mailconv_conversation`.`cls_time`, `lhc_mailconv_conversation`.`pnd_time`, `lhc_mailconv_conversation`.`wait_time`, `lhc_mailconv_conversation`.`accept_time`, `lhc_mailconv_conversation`.`response_time`, `lhc_mailconv_conversation`.`interaction_time`, `lhc_mailconv_conversation`.`tslasign`, `lhc_mailconv_conversation`.`conv_duration`, `lhc_mailconv_conversation`.`follow_up_id`, `lhc_mailconv_conversation`.`has_attachment`, `lhc_mailconv_conversation`.`undelivered`, `lhc_mailconv_conversation`.`pending_sync`, `lhc_mailconv_conversation`.`opened_at` FROM `lhc_mailconv_conversation` WHERE `lhc_mailconv_conversation`.`status` = :ezcValue1 AND (`dep_id` IN (SELECT `id` FROM `lh_departament` WHERE `active_mail_balancing` = 1)) ORDER BY priority DESC, id ASC LIMIT 500 OFFSET 0'",
    "file": "\/var\/www\/html\/lhc\/lhc_web\/ezcomponents\/PersistentObject\/src\/persistent_session.php",
    "line": 833,
    "trace": [
        {
            "file": "\/var\/www\/html\/lhc\/lhc_web\/ezcomponents\/PersistentObject\/src\/handlers\/load_handler.php",
            "line": 269,
            "function": "performQuery",
            "class": "ezcPersistentSession",
            "type": "->",
            "args": [
                {
                    "expr": {}
                }
            ]
        },
        {
            "file": "\/var\/www\/html\/lhc\/lhc_web\/ezcomponents\/PersistentObject\/src\/persistent_session.php",
            "line": 194,
            "function": "find",
            "class": "ezcPersistentLoadHandler",
            "type": "->",
            "args": [
                {
                    "expr": {}
                },
                "erLhcoreClassModelMailconvConversation"
            ]
        },
        {
            "file": "\/var\/www\/html\/lhc\/lhc_web\/lib\/core\/lhcore\/lhdbtrait.php",
            "line": 354,
            "function": "find",
            "class": "ezcPersistentSession",
            "type": "->",
            "args": [
                {}
            ]
        },
        {
            "file": "\/var\/www\/html\/lhc\/lhc_web\/modules\/lhcron\/workflow.php",
            "line": 69,
            "function": "getList",
            "class": "erLhcoreClassModelMailconvConversation",
            "type": "::",
            "args": [
                {
                    "sort": "priority DESC, id ASC",
                    "limit": 500,
                    "customfilter": [
                        "(`dep_id` IN (SELECT `id` FROM `lh_departament` WHERE `active_mail_balancing` = 1))"
                    ],
                    "filter": {
                        "status": 0
                    }
                }
            ]
        },
        {
            "file": "\/var\/www\/html\/lhc\/lhc_web\/cron.php",
            "line": 175,
            "args": [
                "\/var\/www\/html\/lhc\/lhc_web\/modules\/lhcron\/workflow.php"
            ],
            "function": "include_once"
        }
    ],
    "raw": "ezcPersistentQueryException: A query failed internally in Persistent Object: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'livehelperchat.lhc_mailconv_conversation' doesn't exist Query: 'SELECT `lhc_mailconv_conversation`.`id`, `lhc_mailconv_conversation`.`remarks`, `lhc_mailconv_conversation`.`date`, `lhc_mailconv_conversation`.`from_address`, `lhc_mailconv_conversation`.`from_name`, `lhc_mailconv_conversation`.`body`, `lhc_mailconv_conversation`.`subject`, `lhc_mailconv_conversation`.`mail_variables`, `lhc_mailconv_conversation`.`lang`, `lhc_mailconv_conversation`.`phone`, `lhc_mailconv_conversation`.`transfer_uid`, `lhc_mailconv_conversation`.`start_type`, `lhc_mailconv_conversation`.`lr_time`, `lhc_mailconv_conversation`.`dep_id`, `lhc_mailconv_conversation`.`ctime`, `lhc_mailconv_conversation`.`user_id`, `lhc_mailconv_conversation`.`status`, `lhc_mailconv_conversation`.`last_message_id`, `lhc_mailconv_conversation`.`mailbox_id`, `lhc_mailconv_conversation`.`message_id`, `lhc_mailconv_conversation`.`priority`, `lhc_mailconv_conversation`.`priority_asc`, `lhc_mailconv_conversation`.`udate`, `lhc_mailconv_conversation`.`total_messages`, `lhc_mailconv_conversation`.`match_rule_id`, `lhc_mailconv_conversation`.`cls_time`, `lhc_mailconv_conversation`.`pnd_time`, `lhc_mailconv_conversation`.`wait_time`, `lhc_mailconv_conversation`.`accept_time`, `lhc_mailconv_conversation`.`response_time`, `lhc_mailconv_conversation`.`interaction_time`, `lhc_mailconv_conversation`.`tslasign`, `lhc_mailconv_conversation`.`conv_duration`, `lhc_mailconv_conversation`.`follow_up_id`, `lhc_mailconv_conversation`.`has_attachment`, `lhc_mailconv_conversation`.`undelivered`, `lhc_mailconv_conversation`.`pending_sync`, `lhc_mailconv_conversation`.`opened_at` FROM `lhc_mailconv_conversation` WHERE `lhc_mailconv_conversation`.`status` = :ezcValue1 AND (`dep_id` IN (SELECT `id` FROM `lh_departament` WHERE `active_mail_balancing` = 1)) ORDER BY priority DESC, id ASC LIMIT 500 OFFSET 0' in \/var\/www\/html\/lhc\/lhc_web\/ezcomponents\/PersistentObject\/src\/persistent_session.php:833\nStack trace:\n#0 \/var\/www\/html\/lhc\/lhc_web\/ezcomponents\/PersistentObject\/src\/handlers\/load_handler.php(269): ezcPersistentSession->performQuery(Object(ezcQuerySelect))\n#1 \/var\/www\/html\/lhc\/lhc_web\/ezcomponents\/PersistentObject\/src\/persistent_session.php(194): ezcPersistentLoadHandler->find(Object(ezcQuerySelect), 'erLhcoreClassMo...')\n#2 \/var\/www\/html\/lhc\/lhc_web\/lib\/core\/lhcore\/lhdbtrait.php(354): ezcPersistentSession->find(Object(ezcPersistentFindQuery))\n#3 \/var\/www\/html\/lhc\/lhc_web\/modules\/lhcron\/workflow.php(69): erLhcoreClassModelMailconvConversation::getList(Array)\n#4 \/var\/www\/html\/lhc\/lhc_web\/cron.php(175): include_once('\/var\/www\/html\/l...')\n#5 {main}"
}
```

**Comment by comsyspro** [comment]
i got i work again! i had to manually update the database even this is already included in our cronjob update script:

`php cron.php -s site_admin -c cron/util/update_database`

**Comment by remdex** [comment]
Have in mind new version requires composer dependencies now.

**Comment by comsyspro** [comment]
ok, i think porblem solved. we had to update our our cronjob update script. also to overwrite composer files what we haven't done before. and according to this we have updated php version from 7.4 to 8.3 and all works now again. as mentioned the goole map is back but at the moment the visitor location isn't shown on the map. will this also be updated soon?

**Comment by remdex** [comment]
Fix was send. Have in mind php works fine also with 8.3 php version as you had before.

**Comment by comsyspro** [comment]
thank you. it is there again.

![image](https://github.com/LiveHelperChat/livehelperchat/assets/13809377/80a6bf80-4abe-481c-a507-b0cf66e6dedb)
